# Generated by Django 3.1.2 on 2021-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='comments',
            field=models.TextField(max_length=150),
        ),
    ]
