# Generated by Django 3.1.2 on 2021-09-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
