# Generated by Django 3.1.2 on 2021-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210924_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='progress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
