# Generated by Django 3.1.2 on 2021-12-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210927_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='progress',
        ),
    ]
