# Generated by Django 3.1.2 on 2021-12-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
